openapi: 3.0.3
info:
  title: Todo App CLI API
  description: API schema for the Todo App CLI application
  version: 1.0.0
paths:
  /tasks:
    get:
      summary: Get all tasks
      description: Retrieve a list of all tasks with filtering and sorting options
      parameters:
        - name: status
          in: query
          description: Filter tasks by status (complete/incomplete)
          schema:
            type: string
            enum: [complete, incomplete, all]
        - name: priority
          in: query
          description: Filter tasks by priority level
          schema:
            type: string
            enum: [low, medium, high]
        - name: tag
          in: query
          description: Filter tasks by tag
          schema:
            type: string
        - name: sort
          in: query
          description: Sort tasks by field
          schema:
            type: string
            enum: [priority, due_date, alphabetical]
      responses:
        '200':
          description: Successfully retrieved tasks
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      description: Add a new task to the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input data
  /tasks/{id}:
    get:
      summary: Get a specific task
      description: Retrieve a task by its ID
      parameters:
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
      responses:
        '200':
          description: Task found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
    put:
      summary: Update a task
      description: Update an existing task's details
      parameters:
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
    delete:
      summary: Delete a task
      description: Remove a task from the system
      parameters:
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
      responses:
        '204':
          description: Task deleted successfully
        '404':
          description: Task not found
  /tasks/{id}/complete:
    post:
      summary: Mark task as complete
      description: Update a task's status to complete
      parameters:
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
      responses:
        '200':
          description: Task marked as complete
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
  /tasks/search:
    get:
      summary: Search tasks
      description: Search tasks by keyword in title or description
      parameters:
        - name: q
          in: query
          required: true
          description: Search keyword
          schema:
            type: string
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'

components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - status
        - created_date
        - updated_date
      properties:
        id:
          type: string
          description: Unique identifier for the task
          example: "550e8400-e29b-41d4-a716-446655440000"
        title:
          type: string
          description: Task title
          example: "Buy groceries"
        description:
          type: string
          description: Task description
          example: "Milk, bread, eggs"
        status:
          type: string
          enum: [complete, incomplete]
          description: Task completion status
          example: "incomplete"
        priority:
          type: string
          enum: [low, medium, high]
          description: Task priority level
          default: "medium"
          example: "high"
        tags:
          type: array
          items:
            type: string
          description: Array of category tags
          example: ["work", "urgent"]
        due_date:
          type: string
          format: date-time
          description: Optional deadline in ISO 8601 format
          example: "2025-01-01T00:00:00Z"
        created_date:
          type: string
          format: date-time
          description: Timestamp of creation in ISO 8601 format
          example: "2024-12-17T10:00:00Z"
        updated_date:
          type: string
          format: date-time
          description: Timestamp of last modification in ISO 8601 format
          example: "2024-12-17T10:00:00Z"
        recurrence_pattern:
          type: string
          description: Optional recurrence rule for recurring tasks
          example: "daily"

    TaskInput:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          description: Task title (1-200 characters)
          minLength: 1
          maxLength: 200
        description:
          type: string
          description: Task description (0-1000 characters)
          maxLength: 1000
        priority:
          type: string
          enum: [low, medium, high]
          description: Task priority level
          default: "medium"
        tags:
          type: array
          items:
            type: string
            maxLength: 50
          maxItems: 10
          description: Array of category tags
        due_date:
          type: string
          format: date-time
          description: Optional deadline in ISO 8601 format

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          description: New task title (1-200 characters)
          minLength: 1
          maxLength: 200
        description:
          type: string
          description: New task description (0-1000 characters)
          maxLength: 1000
        status:
          type: string
          enum: [complete, incomplete]
          description: New task status
        priority:
          type: string
          enum: [low, medium, high]
          description: New task priority level
        tags:
          type: array
          items:
            type: string
            maxLength: 50
          maxItems: 10
          description: New array of category tags
        due_date:
          type: string
          format: date-time
          description: New deadline in ISO 8601 format