"""Initial models for AI Chatbot

Revision ID: 6e48a7556c38
Revises:
Create Date: 2025-12-24 21:17:38.910669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6e48a7556c38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task', sa.Column('completed', sa.Boolean(), nullable=False))
    op.add_column('task', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('task', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sqlmodel.sql.sqltypes.AutoString(length=500),
               existing_nullable=True)
    op.drop_column('task', 'status')
    op.drop_column('task', 'updated_date')
    op.drop_column('task', 'created_date')
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_constraint('user_better_auth_id_key', 'user', type_='unique')
    op.drop_column('user', 'updated_date')
    op.drop_column('user', 'better_auth_id')
    op.drop_column('user', 'created_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('better_auth_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_better_auth_id_key', 'user', ['better_auth_id'])
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.add_column('task', sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('task', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.drop_column('task', 'updated_at')
    op.drop_column('task', 'created_at')
    op.drop_column('task', 'completed')
    op.drop_table('message')
    op.drop_table('conversation')
    # ### end Alembic commands ###
