"""Add messages column to conversation table

Revision ID: be5ca6f54fec
Revises: 6e48a7556c40
Create Date: 2026-02-02 00:39:08.119592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'be5ca6f54fec'
down_revision: Union[str, None] = '6e48a7556c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aiconfiguration')
    op.add_column('conversation', sa.Column('messages', sa.JSON(), nullable=True))
    op.add_column('conversation', sa.Column('extra_metadata', sa.JSON(), nullable=True))
    op.alter_column('message', 'content',
               existing_type=sa.VARCHAR(length=2000),
               type_=sqlmodel.sql.sqltypes.AutoString(length=500),
               existing_nullable=False)
    op.drop_constraint('message_user_id_fkey', 'message', type_='foreignkey')
    op.drop_column('message', 'user_id')
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sqlmodel.sql.sqltypes.AutoString(length=500),
               existing_nullable=True)
    op.drop_constraint('user_better_auth_id_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_better_auth_id_key', 'user', ['better_auth_id'])
    op.alter_column('task', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.add_column('message', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('message_user_id_fkey', 'message', 'user', ['user_id'], ['id'])
    op.alter_column('message', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=False)
    op.drop_column('conversation', 'extra_metadata')
    op.drop_column('conversation', 'messages')
    op.create_table('aiconfiguration',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('base_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timeout', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fallback_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('fallback_base_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fallback_api_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='aiconfiguration_pkey')
    )
    # ### end Alembic commands ###
